name: Hello World
on: 
  push:
    branches:
      - main
      - develop
      - 'realease/**'
  pull_request:
    branches:
      - main
      - develop
      - 'realease/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo " A demo Build"

